name: 'CI'

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code 🛒
        uses: actions/checkout@v6

      - name: Setup PHP 🐫
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Run tests 🧪
        run: make test

  package:
    runs-on: ubuntu-24.04
    needs: [ test ]
    steps:
      - name: Check out code 🛒
        uses: actions/checkout@v6

      - name: Build plugin zip 📦
        run: make build

      - name: Upload plugin zip ⬆️
        uses: actions/upload-artifact@v4
        with:
          name: poller
          path: build/poller.zip
          if-no-files-found: error
